# **Introduction**

Sebelum sebuah data dapat dianalisis atau digunakan untuk mengambil keputusan kebijakan tentu data tersebut perlu untuk diekstraksi terlebih dahulu. <b>Ekstraksi data</b> adalah sebuah proses pengumpulan atau pengambilan jenis data yang berbeda dari berbagai sumber, banyak di antaranya mungkin tidak terorganisir dengan baik atau tidak terstruktur sama sekali. Proses ini memungkinkan untuk mengkonsolidasikan, memproses, dan menyempurnakan data sehingga nantinya dapat disimpan di lokasi terpusat untuk diubah atau diproses lebih lanjut.

Python sebagai salah satu <i>tools</i> yang <i>powerful</i> untuk pengolahan data menyediakan berbagai <i>library</i> untuk mendukung proses ekstraksi data. Salah satu library paling banyak digunakan adalah <b>pandas</b>.

Pandas memungkinkan untuk membaca data dari berbagai jenis ekstensi seperti data yang bersumber dari database (sql), <i>excel</i> (<b>.xls</b> atau <b>.xlsx</b>), <i>separated value file</i> (<b>.csv</b>, <b>.tsv</b>, dsb) lalu merubahnya menjadi satu format struktur data yang sama yang disebut <b>DataFrame</b>. DataFrame inilah yang nantinya dapat kita lakukan proses <b>Data Manipulation</b><br><br>

<p align="center">
<img src="https://drive.google.com/uc?export=view&id=18NW3gMMTJjkwwpZX5TXi9DTteXxGAoxa" width="600" height="300">
<p align="center"><b>Gambar 1. Proses Ekstraksi Data dengan <i>pandas</i></b></p>

<br><br>
<p align="right"><sup>docs : <i><a href="https://shorturl.at/xyZ69">https://pandas.pydata.org/docs/user_guide/io.html</i></sup></a></p>

##**1. First Step : Pandas**

Untuk dapat menggunakan library pandas pada python, perlu untuk mengimpor library tersebut dengan cara mengetikan sintaks berikut

<p align="center"><code><b>import pandas as pd</b></code></p>

lalu jalankan (<i>run</i>) program.

<br><br>
<p align="left"><sup>docs : <i><a href="https://shorturl.at/kzG06">https://pandas.pydata.org/docs/getting_started/install.html</i></sup></a></p>

### üë®‚Äçüíª Task 1

Ketikan kode `import pandas as pd` pada prompt dibawah ini lalu jalankan

In [1]:
# Write your code below here & exec!
import pandas as pd

# **Struktur Data Pandas**

* Terdapat dua struktur data utama pada library pandas yang disebut dengan Series dan DataFrame.
<p align="center">
<img src="https://datagy.io/wp-content/uploads/2022/12/Understanding-Pandas-Series-and-DataFrames-1024x576.png" width="550" height="289">
<p align="center"><b>Gambar 2. Series VS DataFrame</b></p>
<br>

* Gabungan beberapa Series yang mempunyai banyak baris yang sama dapat membentuk sebuah DataFrame atau berlaku sebaliknya pada sebuah DataFrame dapat dipecah (di-<i>slicing</i> satu kolom) membentuk sebuah Series.<br><br>

<p align="right"><sup>docs : <i><a href="https://shorturl.at/dezQY">http://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html</i></sup></a></p>

##**2. Series**

* <a href="">Series</a> merupakan kolom dari sebuah tabel yang bersifat homogen atau mempunyai elemen dengan tipe data yang sejenis.

* Untuk membuat Series gunakan sintaks berikut

<p align="center"><code><b>pd.Series(data)</b></code></p>

<ul>
  data dapat berupa <i>array-like</i>, <i>Iterable</i>, <i>dict</i>, atau <i>scalar</i>
</ul>

<p align="right"><sup>docs : <i><a href="https://shorturl.at/gmtG2">https://pandas.pydata.org/docs/reference/api/pandas.Series.html</i></sup></a></p>

### üë®‚Äçüíª Task 2 - A

<i>Age of Accounts Receivable</i> (Aging AR) adalah istilah yang merujuk pada lamanya piutang dagang yang masih belum tertagih pada suatu periode tertentu. DQTech mecatat distribusi Aging AR tersaji dari list data sebagai berikut \[78, 91, 40, 50, 95\].

Dari data tersebut buatlah sebuah Series yang disimpan pada variabel dengan nama `ar_aging` lalu tampilkan outputnya!

In [4]:
# Inisialisasi data
data_age_of_AR = [78, 91, 40, 50, 95]

# Write your code below here & exec!
ar_aging = pd.Series(data_age_of_AR)

# Menampilkan hasil
display(ar_aging)

0    78
1    91
2    40
3    50
4    95
dtype: int64

#### _Apakah fungsi `type` yang merupakan fungsi bawaan python bisa digunakan untuk memeriksa tipe data variabel ar_aging (yang notabennya tipe data buatan / bawaan library lain)?_

In [5]:
# Inspeksi tipe data
print(type(ar_aging))

<class 'pandas.core.series.Series'>

### üë®‚Äçüíª Task 2 - B

Dari data Aging AR yang tercatat, akan diberi detail data sebagai berikut
* Cust 1 memiliki Aging AR sebesar 78
* Cust 2 memiliki Aging AR sebesar 91
* Cust 3 memiliki Aging AR sebesar 40
* Cust 4 memiliki Aging AR sebesar 50
* Cust 5 memiliki Aging AR sebesar 95

Dari data tersebut buatlah sebuah Series yang disimpan pada variabel dengan nama `detail_ar_aging` lalu tampilkan outputnya!

In [6]:
# Inisialisasi data
data_age_of_AR = {
    'Cust1' : 78,
    'Cust2' : 91,
    'Cust3' : 40,
    'Cust4' : 50,
    'Cust5' : 95
}

# Write your code below here & exec!
detail_ar_aging = pd.Series(data_age_of_AR)

# Tampilkan hasilnya
display(detail_ar_aging)

Cust1    78
Cust2    91
Cust3    40
Cust4    50
Cust5    95
dtype: int64

## **3. DataFrame**

* <a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">DataFrame</a> adalah struktur data 2 dimensi yang terdiri dari baris dan kolom (seperti tabel) dan dapat menyimpan data dari berbagai jenis (termasuk karakter, bilangan bulat, bilangan real, data kategorikal, dan lainnya).

<p align="center">
<img src="https://www.w3resource.com/w3r_images/pandas-data-frame.svg" width="600" height="300">
<p align="center"><b>Gambar 2. DataFrame Pandas</b></p>
<br>

* <a href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series">Series</a> merupakan kolom dari sebuah tabel yang bersifat homogen atau mempunyai elemen dengan tipe data yang sejenis.


<p align="center">
<img src="https://datagy.io/wp-content/uploads/2022/12/Understanding-Pandas-Series-and-DataFrames-1024x576.png" width="550" height="300">
<p align="center"><b>Gambar 3. Series VS DataFrame</b></p>
<br>

* Gabungan beberapa Series yang mempunyai banyak baris yang sama dapat membentuk sebuah DataFrame atau berlaku sebaliknya pada sebuah DataFrame dapat dipecah (di-<i>slicing</i> satu kolom) membentuk sebuah Series.<br><br>

### üë®‚Äçüíª Task 3

Data karyawan DQTech disajikan pada dictionary berikut

```
details = {
    'Name' : ['Aksara', 'Antara', 'Sendja', 'Sunyi'],
    'Age' : [23, 21, 22, 21],
    'Role' : ['Jr. Data Scientist', 'Data Engineer', 'Data Analyst', 'Data Scientist']
}
```

konversi dictionary tersebut menjadi DataFrame pandas

In [15]:
# Import library
import pandas as pd

# Initialize Data
details = {
    'Name' : ['Aksara', 'Antara', 'Sendja', 'Sunyi'],
    'Age'  : [23, 21, 22, 21],
    'Role' : ['Jr. Data Scientist', 'Data Engineer', 'Data Analyst', 'Data Scientist']
}

# Write your code below here & exec!
dqtech_employee = pd.DataFrame(details)

# Tampilkan data
display(dqtech_employee)

     Name  Age                Role
0  Aksara   23  Jr. Data Scientist
1  Antara   21       Data Engineer
2  Sendja   22        Data Analyst
3   Sunyi   21      Data Scientist

## **4. Parts Of DataFrame**

Untuk lebih memahami objek DataFrame, perlu diketahui bahwa DataFrame terdiri dari tiga komponen sebagai atribut berikut :

<ul>1Ô∏è‚É£ .values : Nilai - nilai yang tertera pada DataFrame</ul>
<ul>2Ô∏è‚É£ .columns : Nama kolom yang ada pada DataFrame</ul>
<ul>3Ô∏è‚É£ .index : Nama atau nomor index pada DataFrame</ul>

### üë®‚Äçüíª Task 4

Pada DataFrame yang telah dibuat pada Task 3, coba buatkan list nama kolomnya!

In [21]:
# Write your code below here & exec!
dqtech_employee.columns

Index(['Name', 'Age', 'Role'], dtype='object')

tampilkan juga nilai (data) nya!

In [20]:
# Write your code below here & exec!
dqtech_employee.values

array([['Aksara', 23, 'Jr. Data Scientist'],
       ['Antara', 21, 'Data Engineer'],
       ['Sendja', 22, 'Data Analyst'],
       ['Sunyi', 21, 'Data Scientist']], dtype=object)

Sekalian indexnya deh wkwk üï∫

In [19]:
# Write your code below here & exec!
dqtech_employee.index

RangeIndex(start=0, stop=4, step=1)

---

# **Data Manipulation**

Data Manipulation adalah sebuah metode pengorganisasian data agar lebih mudah dibaca, terstruktur dan agar lebih mudah diolah untuk kebutuhan lain kedepannya. Beberapa hal yang biasa dilakukan saat data manipulation adalah sebagai berikut :


<ul>1Ô∏è‚É£ Column selections</ul>
<ul>2Ô∏è‚É£ Filter the data</ul>
<ul>3Ô∏è‚É£ Create a new column or change it</ul>
<ul>4Ô∏è‚É£ Drop a column</ul>
<ul>5Ô∏è‚É£ Apply custom functions</ul>
<ul>6Ô∏è‚É£ Join / Merge the data</ul>
<ul>7Ô∏è‚É£ etc</ul>

## **5. Data Extraction**

* Dalam konteks data extraction, Pandas dapat digunakan untuk membaca data dari berbagai sumber, seperti file CSV, Excel, SQL database, dan lainnya, dan mengubahnya menjadi DataFrames untuk analisis lebih lanjut.

* Beberapa fungsi dan metode Pandas yang umum digunakan untuk data extraction adalah sebagai berikut:

<ul>
<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html">pd.read_csv()</a></code>: Digunakan untuk membaca data dari file CSV dan mengonversinya menjadi DataFrame.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html">pd.read_excel()</a></code>: Membaca data dari file Excel dan membuat DataFrame dari lembar kerja atau tabel tertentu.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html">pd.read_sql()</a></code>: Mengambil data dari basis data SQL menggunakan SQL query dan menyimpannya dalam bentuk DataFrame.
</ul>

### üë®‚Äçüíª Task 5

Untuk melakukan proses ekstraksi data, lakukan instruksi berikut :     

1.   Lakukan proses autentikasi dengan menjalankan kode dibawah ini hingga muncul tampilan

![image.png]()

lakukan hingga proses autentikasi berhasil

In [24]:
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

2. Copy project-id lalu masukan ke variabel project_id dibawah ini

![image.png]()

In [29]:
# Buat BigQuery client
project_id = 'dqlab-468906'
client = bigquery.Client(project = project_id)

3. Lakukan proses ekstraksi data dengan mengeksekusi kode berikut

In [28]:
# Inisialisasi query yang akan dijalankan
query = "SELECT * FROM dqlab-468906.pilotclass.tbl_superstore"

# Proses ekstraksi data dari BigQuery ke pandas
data_superstore = client.query(query).to_dataframe()

# Tampilkan hasil
data_superstore.sample(10)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
1964,3009,CA-2016-124772,05/12/2016,6122016,First Class,JG-15160,James Galang,Consumer,United States,Murray,...,42071,South,FUR-FU-10004748,Furniture,Furnishings,"Howard Miller 16"" Diameter Gallery Wall Clock",191.820,3,0.0,74.8098
6057,7783,CA-2016-162236,04/11/2016,6112016,Second Class,ER-13855,Elpida Rittenbach,Corporate,United States,Charlotte,...,28205,South,OFF-ST-10003442,Office Supplies,Storage,Eldon Portable Mobile Manager,45.248,2,0.2,3.9592
1638,7192,CA-2016-116918,01/10/2016,6102016,Second Class,JK-15205,Jamie Kunitz,Consumer,United States,Hialeah,...,33012,South,OFF-BI-10004140,Office Supplies,Binders,Avery Non-Stick Binders,5.388,4,0.7,-4.4900
7088,5374,CA-2015-118738,24/10/2015,30102015,Standard Class,AG-10495,Andrew Gjertsen,Corporate,United States,Houston,...,77041,Central,FUR-TA-10002607,Furniture,Tables,KI Conference Tables,347.361,7,0.3,-69.4722
49,2153,CA-2015-123505,22/11/2015,26112015,Standard Class,AR-10540,Andy Reiter,Consumer,United States,Quincy,...,2169,East,OFF-PA-10002586,Office Supplies,Paper,Xerox 1970,14.940,3,0.0,7.0218
3824,2252,CA-2015-116092,15/02/2015,18022015,Second Class,JM-16195,Justin MacKendrick,Consumer,United States,Los Angeles,...,90004,West,OFF-PA-10000477,Office Supplies,Paper,Xerox 22,19.440,3,0.0,9.3312
985,933,CA-2017-114216,02/09/2017,6092017,Standard Class,RK-19300,Ralph Kennedy,Consumer,United States,Philadelphia,...,19140,East,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",12.192,3,0.2,4.1148
9814,8575,CA-2014-159849,19/09/2014,19092014,Same Day,JK-15640,Jim Kriz,Home Office,United States,San Francisco,...,94110,West,OFF-FA-10000053,Office Supplies,Fasteners,Revere Boxed Rubber Bands by Revere,5.670,3,0.0,0.1134
2463,3995,CA-2015-105627,08/03/2015,12032015,Standard Class,DK-12895,Dana Kaydos,Consumer,United States,Kenosha,...,53142,Central,FUR-BO-10002916,Furniture,Bookcases,"Rush Hierlooms Collection 1"" Thick Stackable B...",512.940,3,0.0,97.4586
2733,8111,CA-2017-160122,18/11/2017,23112017,Standard Class,RD-19930,Russell D'Ascenzo,Consumer,United States,Chicago,...,60623,Central,FUR-CH-10000422,Furniture,Chairs,Global Highback Leather Tilter in Burgundy,127.386,2,0.3,-25.4772

## **6. Inspecting Data Information**

* Untuk dapat menginspeksi informasi umum pada data dapat menggunakan sintaks berikut

<p align="center"><code><b>DataFrame.info()</b></code></p>

<ul>Ketika dijalankan, sintaks tersebut akan menghasilkan output informasi umum pada data seperti banyak kolom, nama kolom beserta tipe data dan jumlah data tak kosong (<i>non-null value</i>)</ul><br>

<p align="right"><sup>docs : <i><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html">https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html</i></sup></a></p>

### üë®‚Äçüíª Task 6

Inspeksi informasi umum pada data yang telah diekstraksi dan telah disimpan pada variabel <code>data_superstore</code>. Setelah itu coba uraikan informasi apa yang bisa anda dapatkan setelah melakukan inspeksi informasi umum pada <code>data_superstore</code>?

In [33]:
# Write your code below here & exec!
data_superstore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   Int64
 1   order_id       9994 non-null   object
 2   order_date     9994 non-null   object
 3   ship_date      9994 non-null   Int64
 4   ship_mode      9994 non-null   object
 5   customer_id    9994 non-null   object
 6   customer_name  9994 non-null   object
 7   segment        9994 non-null   object
 8   country        9994 non-null   object
 9   city           9994 non-null   object
 10  state          9994 non-null   object
 11  postal_code    9994 non-null   Int64
 12  region         9994 non-null   object
 13  product_id     9994 non-null   object
 14  category       9994 non-null   object
 15  sub-category   9994 non-null   object
 16  product_name   9994 non-null   object
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   Int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: Int64(4), float64(3), object(14)
memory usage: 1.6+ MB

## **7. Data Selection**

* Untuk memilih kolom tertentu pada sebuah DataFrame dapat menggunakan sintaks berikut

<p align="center"><code><b>DataFrame.loc[baris , nama_kolom]</b></code></p>

* <code>baris</code>
<ul>
  <li>Gunakan simbol ( : ) untuk menampilkan semua data</li>
  <li>Gunakan simbol (m : n) untuk menampilkan data dari index ke - m sampai dengan index ke - n</li>
</ul>

* <code>nama_kolom</code>
<ul>
  <li>Gunakan string untuk mengakses satu kolom saja (<i>return : Series</i>)</li>
  <li>Gunakan list untuk mengakses lebih dari satu kolom  (<i>return : DataFrame</i>)</li>
</ul>

### üë®‚Äçüíª Task 7 - A

Pada DataFrame <code>data_superstore</code>, simpan 10 data teratas ke dalam variabel **order_id** untuk kolom **Order_ID** saja. Kemudian tampilkan data tersebut!

In [41]:
# Write your code below here & exec!
order_id = data_superstore.loc[:9,'order_id']

# Tampilkan hasilnya
display(order_id)

0    CA-2015-154900
1    CA-2015-154900
2    US-2016-152415
3    US-2016-152415
4    CA-2016-153269
5    CA-2016-153269
6    CA-2016-153269
7    CA-2016-153269
8    CA-2015-158792
9    CA-2016-141082
Name: order_id, dtype: object

### üë®‚Äçüíª Task 7 - B

Pada DataFrame <code>data_superstore</code>, tampilkan data dengan index ke-2 sampai dengan index ke-5 kolom **Order_ID**, **Sales**, **Profit** saja

In [48]:
# Write your code below here & exec!
col_selection = ['order_id','sales','profit']
data_sales = data_superstore.loc[2:5, col_selection]

# Tqampilkan hasilnya
display(data_sales)

         order_id   sales   profit
2  US-2016-152415   14.82   6.2244
3  US-2016-152415  191.82  61.3824
4  CA-2016-153269   11.21   3.3630
5  CA-2016-153269  354.90  88.7250

atau secara sederhana anda dapat menggunakan `DataFrame[nama_kolom]` untuk menghasilkan sebuah Series satu kolom dan `DataFrame[[nama_kolom1, nama_kolom2, ...]]` untuk menseleksi banyak kolom kedalam bentuk DataFrame

### üë®‚Äçüíª Task 7 - C

Pada DataFrame <code>data_superstore</code>, simpan ke dalam variabel **order_id** untuk kolom **Order_ID** saja (gunakan seleksi sederhana). Kemudian tampilkan data tersebut!

In [53]:
# Write your code below here & exec!
order_id = data_superstore.loc[:,'order_id']

display(order_id)

0       CA-2015-154900
1       CA-2015-154900
2       US-2016-152415
3       US-2016-152415
4       CA-2016-153269
             ...
9989    US-2016-158680
9990    CA-2015-150511
9991    US-2014-131982
9992    CA-2016-155488
9993    CA-2017-145506
Name: order_id, Length: 9994, dtype: object

##**8. Conditions**

* Salah satu teknik paling sederhana untuk menemukan bagian mana dari kumpulan data yang menarik adalah menemukan subset baris yang cocok dengan beberapa kriteria untuk difilter atau dipilih. Untuk melakukan hal ini cukup mudah yakni dengan menuliskan kondisi seperti berikut

<p align="center"><code><b>DataFrame.loc[conditions]</b></code></p>

* Conditions dapat dibentuk dari 1 atau lebih kriteria boolean dan dihubungkan dengan operator logika and (&), or (|) atau not (~)

<br>

docs : <i>https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html</i>

### üë®‚Äçüíª Task 8 - A

Pada DataFrame `data_superstore` tampilkan semua record data yang terjadi di 'Los Angeles' saja

In [55]:
# Write your code below here & exec!

# Assign conditions
conditions = (data_superstore['city'] == 'Los Angeles')

# Filter
data_LA = data_superstore.loc[conditions]

# Tampilkeun
display(data_LA)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
3801,63,CA-2015-135545,24/11/2015,30112015,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,90004,West,TEC-AC-10004633,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,13.980,2,0.0,6.1512
3802,64,CA-2015-135545,24/11/2015,30112015,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,90004,West,OFF-BI-10001078,Office Supplies,Binders,"Acco PRESSTEX Data Binder with Storage Hooks, ...",25.824,6,0.2,9.3612
3803,65,CA-2015-135545,24/11/2015,30112015,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,90004,West,OFF-PA-10003892,Office Supplies,Paper,Xerox 1943,146.730,3,0.0,68.9631
3804,66,CA-2015-135545,24/11/2015,30112015,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,90004,West,FUR-FU-10000397,Furniture,Furnishings,Luxo Economy Swing Arm Lamp,79.760,4,0.0,22.3328
3805,172,CA-2014-118962,05/08/2014,9082014,Standard Class,CS-12130,Chad Sievert,Consumer,United States,Los Angeles,...,90004,West,OFF-PA-10000659,Office Supplies,Paper,"Adams Phone Message Book, Professional, 400 Me...",20.940,3,0.0,9.8418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,8174,CA-2014-114125,09/07/2014,13072014,Standard Class,GH-14410,Gary Hansen,Home Office,United States,Los Angeles,...,90049,West,OFF-BI-10003291,Office Supplies,Binders,Wilson Jones Leather-Like Binders with DublLoc...,41.904,6,0.2,14.1426
9664,8175,CA-2014-114125,09/07/2014,13072014,Standard Class,GH-14410,Gary Hansen,Home Office,United States,Los Angeles,...,90049,West,OFF-ST-10001505,Office Supplies,Storage,"Perma STOR-ALL Hanging File Box, 13 1/8""W x 12...",23.920,4,0.0,4.0664
9665,8504,CA-2014-164903,20/02/2014,24022014,Standard Class,SR-20740,Steven Roelle,Home Office,United States,Los Angeles,...,90049,West,OFF-PA-10003363,Office Supplies,Paper,Xerox 204,12.960,2,0.0,6.2208
9666,9141,CA-2017-123029,30/09/2017,2102017,Second Class,BT-11530,Bradley Talbott,Home Office,United States,Los Angeles,...,90049,West,TEC-AC-10002402,Technology,Accessories,Razer Kraken PRO Over Ear PC and Music Headset,159.980,2,0.0,47.9940
9667,9229,CA-2014-153619,03/11/2014,3112014,Same Day,TC-21535,Tracy Collins,Home Office,United States,Los Angeles,...,90049,West,OFF-AR-10001868,Office Supplies,Art,Prang Dustless Chalk Sticks,6.720,4,0.0,3.3600

### üë®‚Äçüíª Task 8 - B

Pada DataFrame `data_superstore` tampilkan semua record data yang terjadi di 'Los Angeles' untuk kategori Technology

In [66]:
# Write your code below here & exec!

# Assign conditions
conditions1 = (data_superstore['city'] == 'Los Angeles')
conditions2 = (data_superstore['category'] == 'Technology')

# Filter
data_LA = data_superstore[conditions1 & conditions2]

# Tampilkeun
display(data_LA)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
3801,63,CA-2015-135545,24/11/2015,30112015,Standard Class,KM-16720,Kunst Miller,Consumer,United States,Los Angeles,...,90004,West,TEC-AC-10004633,Technology,Accessories,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,13.980,2,0.0,6.1512
3816,1573,US-2014-157385,23/11/2014,25112014,First Class,SC-20095,Sanjit Chand,Consumer,United States,Los Angeles,...,90004,West,TEC-AC-10003280,Technology,Accessories,Belkin F8E887 USB Wired Ergonomic Keyboard,29.990,1,0.0,6.2979
3830,3423,CA-2016-134803,28/05/2016,3062016,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Los Angeles,...,90004,West,TEC-AC-10002217,Technology,Accessories,Imation¬†Clip USB¬†flash drive¬†- 8 GB,131.600,7,0.0,7.8960
3832,3425,CA-2016-134803,28/05/2016,3062016,Standard Class,CL-12565,Clay Ludtke,Consumer,United States,Los Angeles,...,90004,West,TEC-MA-10001972,Technology,Machines,Okidata C331dn Printer,558.400,2,0.2,41.8800
3834,3619,CA-2017-141929,04/09/2017,8092017,Standard Class,RA-19285,Ralph Arnett,Consumer,United States,Los Angeles,...,90004,West,TEC-PH-10002185,Technology,Phones,QVS USB Car Charger 2-Port 2.1Amp for iPod/iPh...,5.560,1,0.2,1.7375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9649,3132,CA-2014-136399,16/12/2014,17122014,First Class,CC-12100,Chad Cunningham,Home Office,United States,Los Angeles,...,90049,West,TEC-PH-10004977,Technology,Phones,GE 30524EE4,627.168,4,0.2,70.5564
9650,4338,CA-2015-125234,27/11/2015,1122015,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Los Angeles,...,90049,West,TEC-AC-10000158,Technology,Accessories,Sony 64GB Class 10 Micro SDHC R40 Memory Card,107.970,3,0.0,22.6737
9652,4620,CA-2017-145219,24/12/2017,25122017,First Class,RM-19675,Robert Marley,Home Office,United States,Los Angeles,...,90049,West,TEC-CO-10001449,Technology,Copiers,Hewlett Packard LaserJet 3310 Copier,2879.952,6,0.2,1007.9832
9660,7816,US-2017-109316,08/06/2017,10062017,First Class,MG-17680,Maureen Gastineau,Home Office,United States,Los Angeles,...,90049,West,TEC-PH-10000307,Technology,Phones,Shocksock Galaxy S4 Armband,17.520,2,0.2,-3.5040
9666,9141,CA-2017-123029,30/09/2017,2102017,Second Class,BT-11530,Bradley Talbott,Home Office,United States,Los Angeles,...,90049,West,TEC-AC-10002402,Technology,Accessories,Razer Kraken PRO Over Ear PC and Music Headset,159.980,2,0.0,47.9940

### üë®‚Äçüíª Task 8 - C

Pada DataFrame `data_superstore` tampilkan record data yang terjadi di 'Los Angeles' untuk kategori Technology. Namun hanya tampilkan kolom 'Order_ID', 'City', 'Category' dan 'Profit'

In [68]:
# Assign conditions
conditions1 = (data_superstore['city'] == 'Los Angeles')
conditions2 = (data_superstore['category'] == 'Technology')
list_shown = ['order_id', 'city' , 'category' , 'profit']

# Filter
data_LA_tech = data_superstore.loc[conditions1 & conditions2, list_shown]

# Tampilkeun
display(data_LA_tech)

            order_id         city    category     profit
3801  CA-2015-135545  Los Angeles  Technology     6.1512
3816  US-2014-157385  Los Angeles  Technology     6.2979
3830  CA-2016-134803  Los Angeles  Technology     7.8960
3832  CA-2016-134803  Los Angeles  Technology    41.8800
3834  CA-2017-141929  Los Angeles  Technology     1.7375
...              ...          ...         ...        ...
9649  CA-2014-136399  Los Angeles  Technology    70.5564
9650  CA-2015-125234  Los Angeles  Technology    22.6737
9652  CA-2017-145219  Los Angeles  Technology  1007.9832
9660  US-2017-109316  Los Angeles  Technology    -3.5040
9666  CA-2017-123029  Los Angeles  Technology    47.9940

[150 rows x 4 columns]

## **9. Sorting Row**

Menemukan data yang menarik dalam sebuah DataFrame seringkali lebih mudah jika dilakukan pengurutan baris datanya. Pengurutan dibagi menjadi dua yakni pengurutan secara `Ascending` (pengurutan naik A ‚Üí Z) dan juga pengurutan secara `Descending` (pengurutan turun Z ‚Üí A). Eksekusi sintaks berikut :

<p align="center"><code><b>DataFrame.sort_values(by[data], ascending=True, ignore_index=False)</b></code></p>

Jika ingin mengurutkan DataFrame pandas dengan memperhatikan argumen

<ul>
<li><b><i>by</i></b> sebagai satu atau lebih kolom yang ingin dijadikan patokan pengurutan</li>

<li><b><i>ascending</i></b> dapat diisikan True jika ingin terurut naik atau False jika ingin terurut turun (dafault : True)</li>

<li><b><i>ignore_index</i></b> dapat diisikan True jika ingin index masih terurut atau False jika indexnya masih dipertahankan sesuai data awal (dafault : False)</li>

</ul><br>

docs : <i>https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html</i>

### üë®‚Äçüíª Task 9 - A

Pada DataFrame `data_superstore`, tampilkan semua record data namun urutkan secara ascending pada kolom Order_ID

In [70]:
# Write your code below here & exec!
data_superstore.sort_values(by=['order_id'], ascending=True, ignore_index=True)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,2718,CA-2014-100006,07/09/2014,13092014,Standard Class,DK-13375,Dennis Kane,Consumer,United States,New York City,...,10024,East,TEC-PH-10002075,Technology,Phones,AT&T EL51110 DECT,377.970,3,0.0,109.6113
1,6288,CA-2014-100090,08/07/2014,12072014,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,...,94122,West,FUR-TA-10003715,Furniture,Tables,Hon 2111 Invitation Series Corner Table,502.488,3,0.2,-87.9354
2,6289,CA-2014-100090,08/07/2014,12072014,Standard Class,EB-13705,Ed Braxton,Corporate,United States,San Francisco,...,94122,West,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",196.704,6,0.2,68.8464
3,9515,CA-2014-100293,14/03/2014,18032014,Standard Class,NF-18475,Neil Franz√∂sisch,Home Office,United States,Jacksonville,...,32216,South,OFF-PA-10000176,Office Supplies,Paper,Xerox 1887,91.056,6,0.2,31.8696
4,3084,CA-2014-100328,28/01/2014,3022014,Standard Class,JC-15340,Jasper Cacioppo,Consumer,United States,New York City,...,10024,East,OFF-BI-10000343,Office Supplies,Binders,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",3.928,1,0.2,1.3257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,5934,US-2017-169551,07/07/2017,9072017,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,...,19120,East,TEC-AC-10002018,Technology,Accessories,AmazonBasics 3-Button USB Wired Mouse,16.776,3,0.2,4.8231
9990,5933,US-2017-169551,07/07/2017,9072017,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,...,19120,East,OFF-ST-10004835,Office Supplies,Storage,Plastic Stacking Crates & Casters,13.392,3,0.2,1.0044
9991,5932,US-2017-169551,07/07/2017,9072017,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,...,19120,East,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,683.988,2,0.4,-113.9980
9992,5930,US-2017-169551,07/07/2017,9072017,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,...,19120,East,FUR-BO-10001519,Furniture,Bookcases,O'Sullivan 3-Shelf Heavy-Duty Bookcases,87.210,3,0.5,-45.3492
9993,5931,US-2017-169551,07/07/2017,9072017,First Class,RL-19615,Rob Lucas,Consumer,United States,Philadelphia,...,19120,East,OFF-PA-10004100,Office Supplies,Paper,Xerox 216,15.552,3,0.2,5.4432

### üë®‚Äçüíª Task 9 - B

Pada DataFrame `data_superstore`, tampilkan semua record data namun urutkan secara descending pada kolom Profit dan urutkan secara ascending pada kolom Quantity

In [73]:
# Write your code below here & exec!
data_superstore.sort_values(by=['profit','quantity'], ascending=[False, True], ignore_index=True)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,postal_code,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit
0,6827,CA-2016-118689,02/10/2016,9102016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
1,8154,CA-2017-140151,23/03/2017,25032017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
2,4191,CA-2017-166709,17/11/2017,22112017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
3,9040,CA-2016-117121,17/12/2016,21122016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
4,4099,CA-2014-116904,23/09/2014,28092014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,4992,US-2017-122714,07/12/2017,13122017,Standard Class,HG-14965,Henry Goldwyn,Corporate,United States,Chicago,...,60653,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,1889.990,5,0.8,-2929.4845
9990,3012,CA-2017-134845,17/04/2017,23042017,Standard Class,SR-20425,Sharelle Roach,Home Office,United States,Louisville,...,80027,West,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,2549.985,5,0.7,-3399.9800
9991,9775,CA-2014-169019,26/07/2014,30072014,Standard Class,LF-17185,Luke Foster,Consumer,United States,San Antonio,...,78207,Central,OFF-BI-10004995,Office Supplies,Binders,GBC DocuBind P400 Electric Binding System,2177.584,8,0.8,-3701.8928
9992,684,US-2017-168116,04/11/2017,4112017,Same Day,GT-14635,Grant Thornton,Corporate,United States,Burlington,...,27217,South,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.980,4,0.5,-3839.9904
9993,7773,CA-2016-108196,25/11/2016,2122016,Standard Class,CS-12505,Cindy Stewart,Consumer,United States,Lancaster,...,43130,East,TEC-MA-10000418,Technology,Machines,Cubify CubeX 3D Printer Double Head Print,4499.985,5,0.7,-6599.9780

## **10. Summarize Data**

Di pandas, method `DataFrame.describe()` digunakan untuk menghasilkan statistik deskriptif dari DataFrame. Metode ini sangat berguna untuk dengan cepat memahami statistik dasar dari data. Berikut adalah statistik utama yang disediakan :

* `Jumlah` : Jumlah nilai non-null dalam setiap kolom.
* `Rata-rata` : Rata-rata aritmetika dari setiap kolom.
* `Standar Deviasi` : Ukuran dispersi nilai-nilai sekitar rata-rata.
* `Minimum` : Nilai minimum dalam setiap kolom.
* `Kuartil 25 (Q1)` : Nilai di bawahnya 25% data berada.
* `Kuartil 50 (Median atau Q2)` : Nilai di bawahnya 50% data berada (yaitu nilai tengah).
* `Kuartil 75 (Q3)` : Nilai di bawahnya 75% data berada.
* `Maksimum` : Nilai maksimum dalam setiap kolom.

### üë®‚Äçüíª Task 10

Pada DataFrame `data_superstore`, lakukan perhitungan statistik deskriptif pada kolom - kolom yang memiliki tipe data numerik

In [76]:
# Write your code below here & exec!
data_superstore.describe()

,row_id,ship_date,postal_code,sales,quantity,discount,profit
count,9994.0,9994.0,9994.0,9994.000000,9994.0,9994.000000,9994.000000
mean,4997.5,15963177.434461,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,8803298.907336,32063.69335,623.245101,2.22511,0.206452,234.260108
min,1.0,1012015.0,1040.0,0.444000,1.0,0.000000,-6599.978000
25%,2499.25,8102017.0,23223.0,17.280000,2.0,0.000000,1.728750
50%,4997.5,16082014.0,56430.5,54.490000,3.0,0.200000,8.666500
75%,7495.75,24042016.0,90008.0,209.940000,5.0,0.200000,29.364000
max,9994.0,31122017.0,99301.0,22638.480000,14.0,0.800000,8399.976000

##**11. Aggregation**

Agregasi data merupakan serangkaian proses yang dilakukan untuk melakukan pengumpulan data dan dinyatakan dalam bentuk ringkasan sebagai contoh menghitung total yang dikelompokkan berdasarkan kategori tertentu, dsb.

Untuk melakukan agregasi gunakan sintaks berikut

<p align="center"><code><b>DataFrame.group_by(by, as_index).agg(kolom_hasil_aggregasi = (kolom_dihitung, jenis_agregasi))</b></code></p>

Jenis agregasi :
* pd.Series.sum = Menghitung total data
* pd.Series.mean = Menghitung rataan data
* pd.Series.max = Menghitung nilai maksimum data
* pd.Series.min = Menghitung nilai minimum data
* pd.Series.nunique = Menghitung jumlah data unik data
* pd.Series.count = Menghitung banyak data

### üë®‚Äçüíª Task 11 - A

Pada DataFrame `data_superstore`, Category produk apakah yang menghasilkan total profit paling tinggi? dan berapa total profit yang didapatkan?

In [84]:
# Write your code below here & exec!
total_profit_per_category = data_superstore.groupby('category')['profit'].sum().sort_values(ascending=False)

# Tampilkan hasil
display(total_profit_per_category)

category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: profit, dtype: float64

Category product dengan profit paling tinggi adalah kategori Technology dengan profit yang dihasilkan sebesar 145454.9481

### üë®‚Äçüíª Task 11 - B

Pada DataFrame `data_superstore`, lakukan perhitungan rataan Profit yang dikelompokkan berdasarkan Segment dan Category barang yang terjual

In [80]:
# Write your code below here & exec!
avg_profit_per_category = data_superstore.groupby(['segment', 'category'])['profit'].mean()

# Tampilkan hasil
display(avg_profit_per_category)

segment      category
Consumer     Furniture           6.281293
             Office Supplies    18.014174
             Technology         74.445646
Corporate    Furniture          11.741201
             Office Supplies    22.102923
             Technology         79.723823
Home Office  Furniture          10.705465
             Office Supplies    24.034439
             Technology         89.152458
Name: profit, dtype: float64

**Written By :** <br>
<a href="https://www.linkedin.com/in/muhammad-rully-muchni-4913b7162/"><img alt="Linked In Link" src="https://img.shields.io/badge/-Muhammad%20Rully%20Muchni-0072b1?style=for-the-badge&logo=None&logoColor=white" align="left"/></a>

<br><br>**for :**

<a href="https://dqlab.id/"><img src="https://dqlab.id/files/dqlab/cache/87e30118ebba5ec7d96f6ea8c9dcc10b_x_118_X_55.png" align="left" /></a>